--- 
development: 
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3
  pool: 5
production: 
  encoding: utf8
  username: root
  adapter: mysql
  host: localhost
  password: 
  database: torrentphobe_production
test: 
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3
  pool: 5
